app = "neo4flix-gateway"
primary_region = "jnb"

[env]
  PORT = "8081"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_081
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 256