server:
  port: ${SERVER_PORT}

spring:
  application:
    name: api-gateway
  config:
    import:
      - optional:classpath:application-secrets.properties
      - optional:file:../identity_service/config/application-identity-service.yml
      - optional:file:/app/config/application.yml
  cloud:
    gateway:
      server:
        webflux:
          default-filters: []

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

rate:
  limit:
    login:
      capacity: ${RATE_LIMIT_LOGIN_CAPACITY}
      refill:
        tokens: ${RATE_LIMIT_LOGIN_REFILL_TOKENS}
        minutes: ${RATE_LIMIT_LOGIN_REFILL_MINUTES}

identity:
  service:
    url: ${IDENTITY_SERVICE_URL}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    io.github.johneliud.api_gateway: INFO
    org.springframework.cloud.gateway: INFO
