server:
  port: 8083

spring:
  application:
    name: api-gateway
  config:
    import: optional:classpath:application-secrets.properties
  autoconfigure:
    exclude:
      - org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=X-User-Id
        - RemoveRequestHeader=X-User-Role

logging:
  level:
    io.github.johneliud.api_gateway: INFO
