server:
  port: 8083

spring:
  application:
    name: api-gateway
  config:
    import: optional:classpath:application-secrets.properties
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=X-User-Id
        - RemoveRequestHeader=X-User-Role

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    io.github.johneliud.api_gateway: INFO
